const SequeLize = require("sequelize");
const sequelize = require("./baseSequelize");
const album = sequelize.define(
    "album",
    {
        albumId:{
            field:'albumId',
            primaryKey:true,
            type:SequeLize.INT,
            allowNull:false
        },
        albumName:{
            field:'userName',
            type:SequeLize.STRING,
            allowNull:false
        },
        categoryName:{
            field:'categoryName',
            type:SequeLize.STRING,
            allowNull:false
        },
        programsCount:{
            field:'programsCount',
            type:SequeLize.INT,
            allowNull:false
        },
        coverUrl:{
            field:'coverUrl',
            type:SequeLize.STRING,
            allowNull:false
        },
        salePrice:{
            field:'salePrice',
            type:SequeLize.INT,
            allowNull:false
        },
        salesCount:{
            field:'salesCount',
            type:SequeLize.INT,
            allowNull:false
        },
        shelfStatus:{
            field:'salesCount',
            type:SequeLize.ENUM(0,1),
            allowNull:false
        }
    },
    {  
        tableName: 'album',  
        timestamps: false,  
        freezeTableName: true  
    }  
);
const albumModel={
    update(){

    },
    delete(){
      
    },
    select(page=1,num=5){
       const start=(page-1)*num;
       album.findAndCountAll({
          'order': "id DESC",
          'limit': num,
          'offset':start
       }).success(result=>{
           console.log("select:")
           console.log(result)
       })
    },
    Init(data){
        const data=[
            {
              "albumId":5,
              "albumName":"郭德纲历年相声2009",
              "programsCount":72,
              "coverUrl":"http://fdfs.xmcdn.com/group31/M07/1E/F2/wKgJX1mBbh3gTJNXAAAs3sDYK_I735_mobile_large.jpg",
              "salePrice":0,
              "salesCount":34,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":6,
              "albumName":"股神巴菲特（喜马拉雅出品）",
              "programsCount":10,
              "coverUrl":"http://fdfs.xmcdn.com/group8/M09/0A/F8/wKgDYVbNVBzQtbdhAALZmdZTTII469_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":7,
              "albumName":"郭德纲历年相声2010",
              "programsCount":91,
              "coverUrl":"http://fdfs.xmcdn.com/group31/M02/1E/A5/wKgJX1mBaWPie7xsAAAtcq8OmKA640_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":8,
              "albumName":"郭德纲2013热门相声选集",
              "programsCount":23,
              "coverUrl":"http://fdfs.xmcdn.com/group3/M0A/34/67/wKgDslMUXAKCEHYTAAQQMCtTKck228_mobile_large.jpg",
              "salePrice":0,
              "salesCount":120,
              "shelfStatus":0,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":9,
              "albumName":"郭德纲单口《蒸骨三验》",
              "programsCount":11,
              "coverUrl":"http://fdfs.xmcdn.com/group28/M04/7F/B6/wKgJXFkpDjmxtHEwAACV3SFdrmM320_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":10,
              "albumName":"郭德纲历年相声2009",
              "programsCount":72,
              "coverUrl":"http://fdfs.xmcdn.com/group31/M07/1E/F2/wKgJX1mBbh3gTJNXAAAs3sDYK_I735_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":11,
              "albumName":"热门郭德纲相声选",
              "programsCount":31,
              "coverUrl":"http://fdfs.xmcdn.com/group3/M03/B2/CF/wKgDslLGdWGxzTv-AAEZmen9QzQ577_mobile_large.jpg",
              "salePrice":0,
              "salesCount":300,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":12,
              "albumName":"郭德纲相声2012全集",
              "programsCount":42,
              "coverUrl":"http://fdfs.xmcdn.com/group1/M00/0B/A5/wKgDrVEfL-vRr_zxAAH9jNm3Ksw625_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":0,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":13,
              "albumName":"德云社相声全集",
              "programsCount":728,
              "coverUrl":"http://fdfs.xmcdn.com/group31/M09/20/E2/wKgJSVmBiHCgQDh3AAApsFjA_e4761_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":14,
              "albumName":"郭德纲于谦相声全集",
              "programsCount":25,
              "coverUrl":"http://fdfs.xmcdn.com/group3/M09/34/94/wKgDsVMUWC-i2BqxAALZkSLeN4o874_mobile_large.jpg",
              "salePrice":0,
              "salesCount":23,
              "shelfStatus":0,
              "categoryName":"人文历史",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":14,
              "albumName":"郭德纲历年相声2009",
              "programsCount":72,
              "coverUrl":"http://fdfs.xmcdn.com/group31/M07/1E/F2/wKgJX1mBbh3gTJNXAAAs3sDYK_I735_mobile_large.jpg",
              "salePrice":0,
              "salesCount":34,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":15,
              "albumName":"股神巴菲特（喜马拉雅出品）",
              "programsCount":10,
              "coverUrl":"http://fdfs.xmcdn.com/group8/M09/0A/F8/wKgDYVbNVBzQtbdhAALZmdZTTII469_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":16,
              "albumName":"郭德纲历年相声2010",
              "programsCount":91,
              "coverUrl":"http://fdfs.xmcdn.com/group31/M02/1E/A5/wKgJX1mBaWPie7xsAAAtcq8OmKA640_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":17,
              "albumName":"郭德纲2013热门相声选集",
              "programsCount":23,
              "coverUrl":"http://fdfs.xmcdn.com/group3/M0A/34/67/wKgDslMUXAKCEHYTAAQQMCtTKck228_mobile_large.jpg",
              "salePrice":0,
              "salesCount":120,
              "shelfStatus":0,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":18,
              "albumName":"郭德纲单口《蒸骨三验》",
              "programsCount":11,
              "coverUrl":"http://fdfs.xmcdn.com/group28/M04/7F/B6/wKgJXFkpDjmxtHEwAACV3SFdrmM320_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":19,
              "albumName":"郭德纲历年相声2009",
              "programsCount":72,
              "coverUrl":"http://fdfs.xmcdn.com/group31/M07/1E/F2/wKgJX1mBbh3gTJNXAAAs3sDYK_I735_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":20,
              "albumName":"热门郭德纲相声选",
              "programsCount":31,
              "coverUrl":"http://fdfs.xmcdn.com/group3/M03/B2/CF/wKgDslLGdWGxzTv-AAEZmen9QzQ577_mobile_large.jpg",
              "salePrice":0,
              "salesCount":300,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":21,
              "albumName":"郭德纲相声2012全集",
              "programsCount":42,
              "coverUrl":"http://fdfs.xmcdn.com/group1/M00/0B/A5/wKgDrVEfL-vRr_zxAAH9jNm3Ksw625_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":0,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            },
            {
              "albumId":22,
              "albumName":"德云社相声全集",
              "programsCount":728,
              "coverUrl":"http://fdfs.xmcdn.com/group31/M09/20/E2/wKgJSVmBiHCgQDh3AAApsFjA_e4761_mobile_large.jpg",
              "salePrice":0,
              "salesCount":0,
              "shelfStatus":1,
              "categoryName":"每日精选",
              "channelName":"喜马拉雅"
            }
        ];
        data.forEach(function(value,index,array){
            album.create(value);
        })
    },
    add(data){
       album.create(data);
    }
}
module.exports = albumModel;